guardian_name = "sharding"
buffer_size = 100000
coordinator_singleton_role_override = true

[passivation]
strategy = "default-idle-strategy"

[coordinator_failure_backoff]
secs = 5
nanos = 0

[retry_interval]
secs = 2
nanos = 0

[handoff_timeout]
secs = 60
nanos = 0

[shard_start_timeout]
secs = 10
nanos = 0

[rebalance_interval]
secs = 10
nanos = 0

[shard_region_query_timeout]
secs = 3
nanos = 0

[coordinator_singleton]
singleton_name = "singleton"