[package]
name = "actor-playgroud"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actor = { path = "../actor-core" }
actor-derive = { path = "../actor-derive" }
tokio = { version = "1.34", features = ["full"] }
anyhow = "1.0"
serde = { version = "1.0.190", features = ["derive"] }
async-trait = "0.1.74"
tracing = "0.1.40"