[pub_sub]
name = "distributed_pub_sub_mediator"
routing_logic = "Random"
removed_time_to_live = { secs = 120, nanos = 0 }
max_delta_elements = 3000
send_to_dead_letters_when_no_subscribers = true

[singleton]
singleton_name = "singleton"

[singleton_proxy]
singleton_name = "singleton"
singleton_identification_interval = { secs = 1, nanos = 0 }
buffer_size = 1000