[mailbox.default]
mailbox_capacity = 5000
stash_capacity = 5000
throughput = 50

[phases.before-service-unbind]
depends_on = []

[phases.service-unbind]
depends_on = ["before-service-unbind"]

[phases.service-requests-done]
depends_on = ["service-unbind"]

[phases.service-stop]
depends_on = ["service-requests-done"]

[phases.before-cluster-shutdown]
depends_on = ["service-stop"]

[phases.cluster-sharding-shutdown-region]
depends_on = ["before-cluster-shutdown"]

[phases.cluster-leave]
depends_on = ["cluster-sharding-shutdown-region"]

[phases.cluster-exiting]
depends_on = ["cluster-leave"]

[phases.cluster-exiting-done]
depends_on = ["cluster-exiting"]

[phases.cluster-shutdown]
depends_on = ["cluster-exiting-done"]

[phases.before-actor-system-terminate]
depends_on = ["cluster-shutdown"]

[phases.actor-system-terminate]
depends_on = ["before-actor-system-terminate"]

[creation_timeout]
secs = 20
nanos = 0